version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
    environment:
      MONGODB_URL: mongodb://mongo:password@mongodb/app
      JWT_SECRET: thisisasamplesecret
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
      REDIS_URL: redis://cache

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - '6379:6379'
    networks:
      - node-network


volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
